[허규빈] 소셜 로그인
wecode-bootcamp-korea/26-2nd-WESELL-backend pull request #4
Opened 2021-11-18 11:43 UTC by Gyubs

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 소셜 로그인
- 유닛테스트

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 프론트 통신을 통해 헤더에서 받아온 토큰을 이용해서 카카오 서버에 유저 정보 요청
2. 이메일 정보를 기준으로 get_or_create 메소드 사용
3. DB에서 확인된 유저는 jwt 발급하여 로그인
4. 유닛테스트를 통해 가상의 데이터로 로그인 성공

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
-카카오 오픈 api 로그인을 통해서 소셜로그인의 전체적인 흐름을 이해할 수 있었습니다
-http 통신 사용시 사용되는 requests 에 대해 알 수 있었습니다
-유닛테스트에 대해 공부해 볼 수 있었습니다

<br />

## :: 기타 질문 및 특이 사항

2021-11-19 06:51 UTC, jamessoun93 requested changes

2021-11-19 06:51 UTC, jamessoun93 commented on wesell/urls.py
> +    path("users/", include("users.urls")),
settings.py -> APPEND_SLASH 옵션 반대로

2021-11-19 06:51 UTC, jamessoun93 commented on users/views.py
> +        ACCESS_TOKEN = request.headers.get('Authorization')
-

2021-11-19 06:51 UTC, jamessoun93 commented on users/views.py
> +        User.objects.get_or_create(
user, created = User.objects.get_or_create(id=1)

2021-11-19 06:51 UTC, jamessoun93 commented on users/views.py
> +        return JsonResponse({'message':'SUCCESS', 'ACCESS_TOKEN': access_token}, status=200)
```suggestion
        return JsonResponse({'message': 'SUCCESS', 'access_token': access_token}, status=200)
```

2021-11-19 06:51 UTC, jamessoun93 commented on users/urls.py
> +    path('signin', KakaoSignInView.as_view()),
```suggestion
    path('/signin', KakaoSignInView.as_view()),
```

2021-11-19 06:51 UTC, jamessoun93 commented on users/tests.py
> +                        }
```suggestion
        class MockedResponse:
            def json(self):
                return {
                    'id': 123456789, 
                    'kakao_account': { 'email' : 'gjrbqls@gmail.com' }
                }
```

2021-11-19 08:46 UTC, Gyubs commented
수정완료했습니다 ~!

2021-11-20 06:35 UTC, jamessoun93 approved these changes
LGTM 👍

2021-11-20 06:35 UTC, merged